#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
name: CI

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

jobs:
  pre-commit:
    name: Pre-commit Checks
    runs-on: linux-amd64-cpu4
    container:
      image: ghcr.io/nvidia/dsx-cds-tools:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install dependencies
        run: uv sync

      - name: Run pre-commit
        run: make pre-commit
